[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "bun run dev"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = [
    "https://ext.same-assets.com/**",
    "https://media.istockphoto.com/**",
    "https://thumbs.dreamstime.com/**",
    "https://freerangestock.com/**"
  ]
