import { NextResponse } from 'next/server'

export async function GET() {
  const mockData = [
    {
      id: 1,
      customerName: "João Silva",
      amount: 1500.00,
      transferDate: "2024-03-27",
      status: "completed",
      transferNumber: "TRF-001",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-27",
      bankName: "Itaú",
      bankCode: "341",
      accountNumber: "12345-6",
      agencyNumber: "1234",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 1500.00
    },
    {
      id: 2,
      customerName: "Maria Santos",
      amount: 2750.50,
      transferDate: "2024-03-27",
      status: "pending",
      transferNumber: "TRF-002",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-27",
      bankName: "Bradesco",
      bankCode: "237",
      accountNumber: "98765-4",
      agencyNumber: "5678",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 2740.50
    },
    {
      id: 3,
      customerName: "Pedro Oliveira",
      amount: 980.00,
      transferDate: "2024-03-26",
      status: "completed",
      transferNumber: "TRF-003",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-26",
      bankName: "Caixa Econômica",
      bankCode: "104",
      accountNumber: "45678-9",
      agencyNumber: "3456",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 980.00
    },
    {
      id: 4,
      customerName: "Ana Costa",
      amount: 3200.00,
      transferDate: "2024-03-26",
      status: "failed",
      transferNumber: "TRF-004",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-26",
      bankName: "Banco do Brasil",
      bankCode: "001",
      accountNumber: "23456-7",
      agencyNumber: "2345",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 3190.00
    },
    {
      id: 5,
      customerName: "Carlos Mendes",
      amount: 850.00,
      transferDate: "2024-03-25",
      status: "completed",
      transferNumber: "TRF-005",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-25",
      bankName: "Santander",
      bankCode: "033",
      accountNumber: "87654-3",
      agencyNumber: "4567",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 850.00
    },
    {
      id: 6,
      customerName: "Beatriz Ferreira",
      amount: 2100.00,
      transferDate: "2024-03-25",
      status: "pending",
      transferNumber: "TRF-006",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-25",
      bankName: "Nubank",
      bankCode: "260",
      accountNumber: "34567-8",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 2090.00
    },
    {
      id: 7,
      customerName: "Rafael Lima",
      amount: 1750.00,
      transferDate: "2024-03-24",
      status: "completed",
      transferNumber: "TRF-007",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-24",
      bankName: "Inter",
      bankCode: "077",
      accountNumber: "76543-2",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 1750.00
    },
    {
      id: 8,
      customerName: "Juliana Alves",
      amount: 2900.00,
      transferDate: "2024-03-24",
      status: "completed",
      transferNumber: "TRF-008",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-24",
      bankName: "BTG Pactual",
      bankCode: "208",
      accountNumber: "65432-1",
      agencyNumber: "1234",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 2890.00
    },
    {
      id: 9,
      customerName: "Marcos Santos",
      amount: 1200.00,
      transferDate: "2024-03-23",
      status: "failed",
      transferNumber: "TRF-009",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-23",
      bankName: "C6 Bank",
      bankCode: "336",
      accountNumber: "54321-0",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 1200.00
    },
    {
      id: 10,
      customerName: "Patricia Silva",
      amount: 2500.00,
      transferDate: "2024-03-23",
      status: "completed",
      transferNumber: "TRF-010",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-23",
      bankName: "Banco Pan",
      bankCode: "623",
      accountNumber: "43210-9",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 2490.00
    },
    {
      id: 11,
      customerName: "Lucas Costa",
      amount: 1800.00,
      transferDate: "2024-03-22",
      status: "completed",
      transferNumber: "TRF-011",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-22",
      bankName: "Banco Original",
      bankCode: "212",
      accountNumber: "32109-8",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 1800.00
    },
    {
      id: 12,
      customerName: "Fernanda Lima",
      amount: 3200.00,
      transferDate: "2024-03-22",
      status: "pending",
      transferNumber: "TRF-012",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-22",
      bankName: "Banco Safra",
      bankCode: "422",
      accountNumber: "21098-7",
      agencyNumber: "1234",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 3190.00
    },
    {
      id: 13,
      customerName: "Gustavo Oliveira",
      amount: 950.00,
      transferDate: "2024-03-21",
      status: "completed",
      transferNumber: "TRF-013",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-21",
      bankName: "Banco Modal",
      bankCode: "746",
      accountNumber: "10987-6",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 950.00
    },
    {
      id: 14,
      customerName: "Mariana Costa",
      amount: 2800.00,
      transferDate: "2024-03-21",
      status: "completed",
      transferNumber: "TRF-014",
      description: "Transferência de lucro",
      paymentMethod: "TED",
      createdAt: "2024-03-21",
      bankName: "Banco Rendimento",
      bankCode: "633",
      accountNumber: "09876-5",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "TED",
      fee: 10.00,
      netAmount: 2790.00
    },
    {
      id: 15,
      customerName: "Roberto Alves",
      amount: 1500.00,
      transferDate: "2024-03-20",
      status: "failed",
      transferNumber: "TRF-015",
      description: "Transferência de lucro",
      paymentMethod: "PIX",
      createdAt: "2024-03-20",
      bankName: "Banco Daycoval",
      bankCode: "707",
      accountNumber: "98765-4",
      agencyNumber: "0001",
      accountType: "Conta Corrente",
      transferType: "PIX",
      fee: 0.00,
      netAmount: 1500.00
    }
  ]

  return NextResponse.json(mockData)
} 