import { NextResponse } from 'next/server'

export async function GET() {
  const mockData = [
    {
      id: 1,
      customerName: "João Silva",
      amount: 1500.00,
      dueDate: "2024-04-15",
      status: "active",
      invoiceNumber: "LINK-001",
      description: "Serviços de consultoria",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-20",
      linkUrl: "https://debita.ai/pay/abc123",
      linkCode: "abc123",
      views: 25,
      clicks: 18,
      sales: 1
    },
    {
      id: 2,
      customerName: "Maria Santos",
      amount: 2750.50,
      dueDate: "2024-04-20",
      status: "expired",
      invoiceNumber: "LINK-002",
      description: "Desenvolvimento de software",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-21",
      linkUrl: "https://debita.ai/pay/def456",
      linkCode: "def456",
      views: 45,
      clicks: 32,
      sales: 2
    },
    {
      id: 3,
      customerName: "Pedro Oliveira",
      amount: 980.00,
      dueDate: "2024-04-10",
      status: "active",
      invoiceNumber: "LINK-003",
      description: "Manutenção de sistema",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-19",
      linkUrl: "https://debita.ai/pay/ghi789",
      linkCode: "ghi789",
      views: 15,
      clicks: 12,
      sales: 0
    },
    {
      id: 4,
      customerName: "Ana Costa",
      amount: 3200.00,
      dueDate: "2024-04-25",
      status: "active",
      invoiceNumber: "LINK-004",
      description: "Projeto de implementação",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-22",
      linkUrl: "https://debita.ai/pay/jkl012",
      linkCode: "jkl012",
      views: 60,
      clicks: 45,
      sales: 3
    },
    {
      id: 5,
      customerName: "Carlos Mendes",
      amount: 850.00,
      dueDate: "2024-04-05",
      status: "paid",
      invoiceNumber: "LINK-005",
      description: "Treinamento técnico",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-18",
      linkUrl: "https://debita.ai/pay/mno345",
      linkCode: "mno345",
      views: 30,
      clicks: 25,
      sales: 1
    },
    {
      id: 6,
      customerName: "Beatriz Ferreira",
      amount: 2100.00,
      dueDate: "2024-04-30",
      status: "active",
      invoiceNumber: "LINK-006",
      description: "Consultoria de segurança",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-23",
      linkUrl: "https://debita.ai/pay/pqr678",
      linkCode: "pqr678",
      views: 40,
      clicks: 30,
      sales: 2
    },
    {
      id: 7,
      customerName: "Rafael Lima",
      amount: 1750.00,
      dueDate: "2024-04-12",
      status: "paid",
      invoiceNumber: "LINK-007",
      description: "Suporte técnico",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-20",
      linkUrl: "https://debita.ai/pay/stu901",
      linkCode: "stu901",
      views: 35,
      clicks: 28,
      sales: 1
    },
    {
      id: 8,
      customerName: "Juliana Alves",
      amount: 2900.00,
      dueDate: "2024-04-28",
      status: "active",
      invoiceNumber: "LINK-008",
      description: "Desenvolvimento de aplicativo",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-21",
      linkUrl: "https://debita.ai/pay/vwx234",
      linkCode: "vwx234",
      views: 50,
      clicks: 38,
      sales: 2
    },
    {
      id: 9,
      customerName: "Marcos Santos",
      amount: 1200.00,
      dueDate: "2024-04-08",
      status: "expired",
      invoiceNumber: "LINK-009",
      description: "Configuração de servidor",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-19",
      linkUrl: "https://debita.ai/pay/yza567",
      linkCode: "yza567",
      views: 20,
      clicks: 15,
      sales: 0
    },
    {
      id: 10,
      customerName: "Patricia Silva",
      amount: 2500.00,
      dueDate: "2024-04-22",
      status: "active",
      invoiceNumber: "LINK-010",
      description: "Implementação de sistema",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-22",
      linkUrl: "https://debita.ai/pay/bcd890",
      linkCode: "bcd890",
      views: 55,
      clicks: 42,
      sales: 3
    },
    {
      id: 11,
      customerName: "Lucas Costa",
      amount: 1800.00,
      dueDate: "2024-04-18",
      status: "paid",
      invoiceNumber: "LINK-011",
      description: "Consultoria de desenvolvimento",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-23",
      linkUrl: "https://debita.ai/pay/efg123",
      linkCode: "efg123",
      views: 40,
      clicks: 35,
      sales: 2
    },
    {
      id: 12,
      customerName: "Fernanda Lima",
      amount: 3200.00,
      dueDate: "2024-04-25",
      status: "active",
      invoiceNumber: "LINK-012",
      description: "Projeto de automação",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-24",
      linkUrl: "https://debita.ai/pay/hij456",
      linkCode: "hij456",
      views: 65,
      clicks: 48,
      sales: 3
    },
    {
      id: 13,
      customerName: "Gustavo Oliveira",
      amount: 950.00,
      dueDate: "2024-04-05",
      status: "expired",
      invoiceNumber: "LINK-013",
      description: "Treinamento de equipe",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-20",
      linkUrl: "https://debita.ai/pay/klm789",
      linkCode: "klm789",
      views: 25,
      clicks: 20,
      sales: 1
    },
    {
      id: 14,
      customerName: "Mariana Costa",
      amount: 2800.00,
      dueDate: "2024-04-15",
      status: "active",
      invoiceNumber: "LINK-014",
      description: "Desenvolvimento de API",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-25",
      linkUrl: "https://debita.ai/pay/nop012",
      linkCode: "nop012",
      views: 45,
      clicks: 35,
      sales: 2
    },
    {
      id: 15,
      customerName: "Roberto Alves",
      amount: 1500.00,
      dueDate: "2024-04-10",
      status: "paid",
      invoiceNumber: "LINK-015",
      description: "Manutenção de sistema",
      paymentMethod: "Link de Pagamento",
      createdAt: "2024-03-26",
      linkUrl: "https://debita.ai/pay/qrs345",
      linkCode: "qrs345",
      views: 35,
      clicks: 28,
      sales: 1
    }
  ]

  return NextResponse.json(mockData)
} 